apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-server
  namespace: mlflow
  labels:
    app: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      nodeSelector:
        kubernetes.io/hostname: minikube
      containers:
      - name: mlflow
        image: ghcr.io/mlflow/mlflow:v2.9.2
        command: ["mlflow", "server"]
        args:
          - "--host=0.0.0.0"
          - "--port=5000"
          - "--backend-store-uri=sqlite:////mlflow/db/mlflow.db"
          - "--default-artifact-root=/mlflow/artifacts"
          - "--serve-artifacts"
        ports:
        - containerPort: 5000
          name: http
        volumeMounts:
        - name: mlflow-artifacts
          mountPath: /mlflow/artifacts
        - name: mlflow-db
          mountPath: /mlflow/db
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: mlflow-artifacts
        persistentVolumeClaim:
          claimName: mlflow-artifacts-pvc
      - name: mlflow-db
        persistentVolumeClaim:
          claimName: mlflow-db-pvc