apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  labels:
    app: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      initContainers:
      - name: install-mlflow
        image: python:3.9-slim
        command:
        - /bin/sh
        - -c
        - |
          pip install mlflow==2.8.1 psycopg2-binary boto3
          cp -r /usr/local/lib/python3.9/site-packages/* /shared/
        volumeMounts:
        - name: shared-packages
          mountPath: /shared
      containers:
      - name: mlflow
        image: python:3.9-slim
        ports:
        - containerPort: 5000
        env:
        - name: PYTHONPATH
          value: "/shared"
        - name: MLFLOW_BACKEND_STORE_URI
          value: "postgresql://mlflow:mlflow123@postgres-postgresql.postgres.svc.cluster.local:5432/mlflow"
        - name: MLFLOW_ARTIFACT_ROOT
          value: "s3://mlflow-artifacts/"
        - name: MLFLOW_S3_ENDPOINT_URL
          value: "http://minio.minio.svc.cluster.local:9000"
        - name: AWS_ACCESS_KEY_ID
          value: "minioadmin"
        - name: AWS_SECRET_ACCESS_KEY
          value: "minioadmin123"
        - name: MLFLOW_S3_IGNORE_TLS
          value: "true"
        command:
        - /bin/sh
        - -c
        - |
          export PYTHONPATH="/shared:$PYTHONPATH"
          cd /shared
          python -m mlflow server \
            --backend-store-uri $MLFLOW_BACKEND_STORE_URI \
            --default-artifact-root $MLFLOW_ARTIFACT_ROOT \
            --host 0.0.0.0 \
            --port 5000
        resources:
          requests:
            memory: 512Mi
            cpu: 100m
          limits:
            memory: 1Gi
            cpu: 500m
        volumeMounts:
        - name: shared-packages
          mountPath: /shared
      volumes:
      - name: shared-packages
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
spec:
  selector:
    app: mlflow
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP