apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mlflow.fullname" . }}-secret
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
type: Opaque
data:
  db-password: {{ .Values.database.password | b64enc }}
  minio-access-key: {{ .Values.minio.accessKey | b64enc }}
  minio-secret-key: {{ .Values.minio.secretKey | b64enc }}