apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow-platform
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  source:
    repoURL: https://github.com/blacklightsun/goit-mlflow-platform.git
    targetRevision: HEAD
    path: apps
    directory:
      recurse: true  # Рекурсивний пошук в підпапках
      include: "*/application.yaml"  # Шукаємо application.yaml в підпапках
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true